# Generated by Django 4.2.5 on 2023-10-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('address', models.TextField()),
                ('role', models.CharField(max_length=128)),
            ],
        ),
    ]
